# Etape 1 - Importation des librairies et chargement des fichiers

### 1.1 - Importation des librairies

In [71]:
# Importation de la librairie Pandas
import pandas as pd

### 1.2 - Chargement des fichiers Excel

In [74]:
# Importation du fichier population.csv
population = pd.read_csv('population.csv')

# Importation du fichier dispo_alimentaire.csv
dispoAlimentaire = pd.read_csv('dispo_alimentaire.csv')

# Importation du fichier aide_alimentaire.csv
aideAlimentaire = pd.read_csv('aide_alimentaire.csv')

# Importation du fichier sous_nutrition.csv
sousNutrition = pd.read_csv('sous_nutrition.csv')

# Etape 2 - Analyse exploratoire des fichiers

### 2.1 - Analyse exploratoire du fichier population

In [78]:
# Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(population.shape[0]))
print("Le tableau comporte {} colonne(s)".format(population.shape[1]))

Le tableau comporte 1416 observation(s) ou article(s)
Le tableau comporte 3 colonne(s)

In [80]:
# Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(population.shape[1]))
# La nature des données dans chacune des colonnes
print(population.dtypes)
# Le nombre de valeurs présentes dans chacune des colonnes
print(population.count())

Le tableau comporte 3 colonne(s)
Zone       object
Année       int64
Valeur    float64
dtype: object
Zone      1416
Année     1416
Valeur    1416
dtype: int64

In [82]:
# Affichage les 5 premières lignes de la table
population.head()

          Zone  Année     Valeur
0  Afghanistan   2013  32269.589
1  Afghanistan   2014  33370.794
2  Afghanistan   2015  34413.603
3  Afghanistan   2016  35383.032
4  Afghanistan   2017  36296.113

In [84]:
# Nous allons harmoniser les unités. Pour cela, nous avons décidé de multiplier la population par 1000
#Multiplication de la colonne valeur par 1000
population['Valeur'] = population['Valeur'] * 1000

In [86]:
# Changement du nom de la colonne Valeur par Population
population.rename(columns={'Valeur':'Population'}, inplace=True)

In [88]:
# Affichage les 5 premières lignes de la table pour voir les modifications
population.head()

          Zone  Année  Population
0  Afghanistan   2013  32269589.0
1  Afghanistan   2014  33370794.0
2  Afghanistan   2015  34413603.0
3  Afghanistan   2016  35383032.0
4  Afghanistan   2017  36296113.0

### 2.2 - Analyse exploratoire du fichier disponibilité alimentaire

In [91]:
# Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(dispoAlimentaire.shape[0]))
print("Le tableau comporte {} colonne(s)".format(dispoAlimentaire.shape[1]))

Le tableau comporte 15605 observation(s) ou article(s)
Le tableau comporte 18 colonne(s)

In [93]:
# Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(dispoAlimentaire.shape[1]))

Le tableau comporte 18 colonne(s)

In [95]:
# Affichage les 5 premières lignes de la table
dispoAlimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,NaN,NaN,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",vegetale,NaN,NaN,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN

In [97]:
# Remplacement des NaN dans le dataset par des 0
dispoAlimentaire.fillna(0, inplace=True)

In [99]:
# Multiplication de toutes les lignes contenant des milliers de tonnes en Kg
colonnes_tonnes_tokg = ['Aliments pour animaux', 'Disponibilité intérieure', 'Exportations - Quantité',
                        'Importations - Quantité', 'Nourriture', 'Pertes', 'Production',
                        'Semences', 'Traitement', 'Variation de stock', 'Autres Utilisations']

for elt in colonnes_tonnes_tokg:
    dispoAlimentaire[elt] *= 1000

In [101]:
# Affichage les 5 premières lignes de la table
dispoAlimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000.0,0.0,0.0,53000.0,0.0,53000.0,0.0,0.0,0.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000.0,2000.0,40000.0,39000.0,2000.0,3000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000.0,0.0,2000.0,2000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000.0,0.0,82000.0,82000.0,0.0,0.0,0.0,0.0,0.0

### 2.3 - Analyse exploratoire du fichier aide alimentaire

In [104]:
# Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(aideAlimentaire.shape[0]))
print("Le tableau comporte {} colonne(s)".format(aideAlimentaire.shape[1]))

Le tableau comporte 1475 observation(s) ou article(s)
Le tableau comporte 4 colonne(s)

In [106]:
# Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(aideAlimentaire.shape[1]))

Le tableau comporte 4 colonne(s)

In [108]:
# Affichage les 5 premières lignes de la table
aideAlimentaire.head()

  Pays bénéficiaire  Année              Produit  Valeur
0       Afghanistan   2013  Autres non-céréales     682
1       Afghanistan   2014  Autres non-céréales     335
2       Afghanistan   2013         Blé et Farin   39224
3       Afghanistan   2014         Blé et Farin   15160
4       Afghanistan   2013             Céréales   40504

In [110]:
# Changement du nom de la colonne Pays bénéficiaire par Zone
aideAlimentaire.rename(columns={'Pays bénéficiaire':'zone'}, inplace=True)

In [112]:
# Multiplication de la colonne Aide_alimentaire qui contient des tonnes par 1000 pour avoir des kg
colonnes_tonnes_tokg = ['Valeur']

for elt in colonnes_tonnes_tokg:
    aideAlimentaire[elt] *= 1000

In [114]:
# Affichage les 5 premières lignes de la table
aideAlimentaire.head()

          zone  Année              Produit    Valeur
0  Afghanistan   2013  Autres non-céréales    682000
1  Afghanistan   2014  Autres non-céréales    335000
2  Afghanistan   2013         Blé et Farin  39224000
3  Afghanistan   2014         Blé et Farin  15160000
4  Afghanistan   2013             Céréales  40504000

### 2.4 - Analyse exploratoire du fichier sous nutrition

In [117]:
# Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(sousNutrition.shape[0]))
print("Le tableau comporte {} colonne(s)".format(sousNutrition.shape[1]))

Le tableau comporte 1218 observation(s) ou article(s)
Le tableau comporte 3 colonne(s)

In [119]:
# Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(sousNutrition.shape[1]))

Le tableau comporte 3 colonne(s)

In [121]:
# Afficher les 5 premières lignes de la table
sousNutrition.head()

          Zone      Année Valeur
0  Afghanistan  2012-2014    8.6
1  Afghanistan  2013-2015    8.8
2  Afghanistan  2014-2016    8.9
3  Afghanistan  2015-2017    9.7
4  Afghanistan  2016-2018   10.5

In [123]:
# Conversion de la colonne sous nutrition en numérique
sousNutrition['Valeur'] = pd.to_numeric(sousNutrition['Valeur'], errors='coerce')

In [125]:
# Conversion de la colonne (avec l'argument errors=coerce qui permet de convertir automatiquement les lignes qui ne sont pas des nombres en NaN)
# Puis remplacement des NaN en 0
sousNutrition['Valeur'] = pd.to_numeric(sousNutrition['Valeur'], errors='coerce').fillna(0)

In [127]:
# Changement du nom de la colonne Valeur par sous_nutrition
sousNutrition.rename(columns={'Valeur':'sous_nutrition'}, inplace=True)

In [129]:
# Multiplication de la colonne sous_nutrition par 1000000
sousNutrition['sous_nutrition'] = sousNutrition['sous_nutrition'] * 1000000

In [131]:
# Afficher les 5 premières lignes de la table
sousNutrition.head()

          Zone      Année  sous_nutrition
0  Afghanistan  2012-2014       8600000.0
1  Afghanistan  2013-2015       8800000.0
2  Afghanistan  2014-2016       8900000.0
3  Afghanistan  2015-2017       9700000.0
4  Afghanistan  2016-2018      10500000.0

# Etape 3 - Analyses

### 3.1 - Proportion de personnes en sous nutrition

In [135]:
# Il faut tout d'abord faire une jointure entre la table population et la table sous nutrition, en ciblant l'année 2017
sousNutrition2017 = pd.merge(population.loc[population['Année'] == 2017, ["Zone", "Population"]], sousNutrition.loc[sousNutrition['Année'] == '2016-2018',["Zone", "sous_nutrition"]], on='Zone')

In [137]:
# Affichage du dataset
sousNutrition2017.head()

             Zone  Population  sous_nutrition
0     Afghanistan  36296113.0      10500000.0
1  Afrique du Sud  57009756.0       3100000.0
2         Albanie   2884169.0        100000.0
3         Algérie  41389189.0       1300000.0
4       Allemagne  82658409.0             0.0

In [139]:
# Calcul et affichage du nombre de personnes en état de sous nutrition
print("Proportion de personnes en état de sous nutrition :", "{:.2f}".format(sousNutrition2017['sous_nutrition'].sum()*100/sousNutrition2017['Population'].sum()), "%")

Proportion de personnes en état de sous nutrition : 7.10 %

In [142]:
# Il faut tout d'abord faire une jointure entre la table population et la table sous nutrition, en ciblant l'année 2013
sousNutrition2013 = pd.merge(population.loc[population['Année'] == 2013, ["Zone", "Population"]], sousNutrition.loc[sousNutrition['Année'] == '2012-2014',["Zone", "sous_nutrition"]], on='Zone')

In [144]:
# Calcul et affichage du nombre de personnes en état de sous nutrition
print("Proportion de personnes en état de sous nutrition :", "{:.2f}".format(sousNutrition2013['sous_nutrition'].sum()*100/sousNutrition2013['Population'].sum()), "%")

Proportion de personnes en état de sous nutrition : 7.33 %

In [146]:
# Il faut tout d'abord faire une jointure entre la table population et la table sous nutrition, en ciblant l'année 2014
sousNutrition2014 = pd.merge(population.loc[population['Année'] == 2014, ["Zone", "Population"]], sousNutrition.loc[sousNutrition['Année'] == '2013-2015',["Zone", "sous_nutrition"]], on='Zone')

In [148]:
# Calcul et affichage du nombre de personnes en état de sous nutrition
print("Proportion de personnes en état de sous nutrition :", "{:.2f}".format(sousNutrition2014['sous_nutrition'].sum()*100/sousNutrition2014['Population'].sum()), "%")

Proportion de personnes en état de sous nutrition : 7.18 %

In [150]:
# Il faut tout d'abord faire une jointure entre la table population et la table sous nutrition, en ciblant l'année 2015
sousNutrition2015 = pd.merge(population.loc[population['Année'] == 2015, ["Zone", "Population"]], sousNutrition.loc[sousNutrition['Année'] == '2014-2016',["Zone", "sous_nutrition"]], on='Zone')

In [152]:
# Calcul et affichage du nombre de personnes en état de sous nutrition
print("Proportion de personnes en état de sous nutrition :", "{:.2f}".format(sousNutrition2015['sous_nutrition'].sum()*100/sousNutrition2015['Population'].sum()), "%")

Proportion de personnes en état de sous nutrition : 7.11 %

In [154]:
# Il faut tout d'abord faire une jointure entre la table population et la table sous nutrition, en ciblant l'année 2016
sousNutrition2016 = pd.merge(population.loc[population['Année'] == 2016, ["Zone", "Population"]], sousNutrition.loc[sousNutrition['Année'] == '2015-2017',["Zone", "sous_nutrition"]], on='Zone')

In [156]:
# Calcul et affichage du nombre de personnes en état de sous nutrition
print("Proportion de personnes en état de sous nutrition :", "{:.2f}".format(sousNutrition2016['sous_nutrition'].sum()*100/sousNutrition2016['Population'].sum()), "%")

Proportion de personnes en état de sous nutrition : 7.09 %

### 3.2 - Nombre théorique de personne qui pourrait être nourries

In [159]:
# Combien mange en moyenne un être humain ? Source => 
moyenneNourriture = dispoAlimentaire['Disponibilité alimentaire (Kcal/personne/jour)'].mean() 
print(moyenneNourriture)

31.748926626081385

In [161]:
# On commence par faire une jointure entre le data frame population et Dispo_alimentaire afin d'ajouter dans ce dernier la population
dispoAlimentaire = dispoAlimentaire.merge(population.loc[population['Année'] == 2017,["Zone", "Population"]], on='Zone')

In [163]:
# Affichage du nouveau dataframe
dispoAlimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Population
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000.0,0.0,0.0,53000.0,0.0,53000.0,0.0,0.0,0.0,36296113.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000.0,2000.0,40000.0,39000.0,2000.0,3000.0,0.0,0.0,0.0,36296113.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000.0,0.0,2000.0,2000.0,0.0,0.0,0.0,0.0,0.0,36296113.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36296113.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000.0,0.0,82000.0,82000.0,0.0,0.0,0.0,0.0,0.0,36296113.0

In [165]:
# Création de la colonne dispo_kcal avec calcul des kcal disponibles mondialement
dispoAlimentaire['dispo_kcal'] = dispoAlimentaire['Disponibilité alimentaire (Kcal/personne/jour)'] * dispoAlimentaire['Population'] * 365
print("dispo alimentaire totale en kcal :", dispoAlimentaire['dispo_kcal'].sum(), "kcal")

dispo alimentaire totale en kcal : 7635429388975815.0 kcal

In [167]:
# Calcul du nombre d'humains pouvant être nourris
total_h_kcal = round(dispoAlimentaire['dispo_kcal'].sum()/(2250*365))
print("Total d'être humain pouvant être nourris :", total_h_kcal)
print("Proportion :", "{:.2f}".format(total_h_kcal*100/population.loc[population['Année'] == 2017,"Population"].sum()), "%")

Total d'être humain pouvant être nourris : 9297326501
Proportion : 123.17 %

### 3.3 - Nombre théorique de personne qui pourrait être nourrie avec les produits végétaux

In [170]:
# Transfert des données avec les végétaux dans un nouveau dataframe
vegetaux = dispoAlimentaire.loc[dispoAlimentaire['Origine'] == "vegetale",:]

In [172]:
# Calcul du nombre de kcal disponible pour les végétaux
print("dispo alimentaire totale en kcal des produits végétaux :", vegetaux['dispo_kcal'].sum(), "kcal")

dispo alimentaire totale en kcal des produits végétaux : 6300178937197865.0 kcal

In [174]:
# Calcul du nombre d'humains pouvant être nourris avec les végétaux
total_h_kcal = round(vegetaux['dispo_kcal'].sum()/(2250*365))
print("Total d'être humain pouvant être nourris :", total_h_kcal)
print("Proportion :", "{:.2f}".format(total_h_kcal*100/population.loc[population['Année'] == 2017,"Population"].sum()), "%")

Total d'être humain pouvant être nourris : 7671450761
Proportion : 101.63 %

### 3.4 - Utilisation de la disponibilité intérieure

In [177]:
# Calcul de la disponibilité totale
dispoTotal = round(dispoAlimentaire['Disponibilité intérieure'].sum())
print("Total de la disponibilité intérieur :", dispoTotal)

Total de la disponibilité intérieur : 9733927000

In [179]:
# Création d'une boucle for pour afficher les différentes valeurs en fonction des colonnes aliments pour animaux, pertes, nourritures, 
for i in ['Aliments pour animaux', 'Pertes', 'Nourriture', 'Semences', 'Traitement', 'Autres Utilisations']:
    print("La proportion de", i, ":", "{:.2f}".format(dispoAlimentaire[i].sum()*100/dispoTotal), "%")

La proportion de Aliments pour animaux : 13.23 %
La proportion de Pertes : 4.65 %
La proportion de Nourriture : 49.37 %
La proportion de Semences : 1.58 %
La proportion de Traitement : 22.45 %
La proportion de Autres Utilisations : 8.82 %

### 3.5 - Utilisation des céréales

In [182]:
# Création d'une liste avec toutes les variables
liste_céréales = ["Blé", "Riz (Eq Blanchi)", "Orge", "Maïs", "Seigle",
                  "Avoine", "Millet", "Sorgho", "Céréales", "Autres"]

In [184]:
# Création d'un dataframe avec les informations uniquement pour ces céréales
céréales = dispoAlimentaire.loc[dispoAlimentaire["Produit"].isin(liste_céréales),:]

In [186]:
# Affichage de la proportion d'alimentation animale
print("Proportion alimentation animals :", "{:.2f}".format(céréales["Aliments pour animaux"].sum()*100/céréales['Disponibilité intérieure'].sum()), "%")

Proportion alimentation animals : 35.76 %

In [188]:
# Affichage de la proportion d'alimentation humaine
print("Proportion alimentation humaine :", "{:.2f}".format(céréales["Nourriture"].sum()*100/céréales['Disponibilité intérieure'].sum()), "%")

Proportion alimentation humaine : 43.18 %

### 3.6 - Pays avec la proportion de personnes sous-alimentée la plus forte en 2017

In [191]:
# Création de la colonne proportion par pays
sousNutrition['proportion par pays'] = round(sousNutrition['sous_nutrition']*100/sousNutrition['Population'])

KeyError: 'Population'

In [ ]:
# Affichage après trie des 10 pires pays
sousNutrition.nlargest(10, 'proportion par pays')

### 3.7 - Pays qui ont le plus bénéficié d'aide alimentaire depuis 2013

In [110]:
# Calcul du total de l'aide alimentaire par pays
aide_pays = aideAlimentaire[['zone','Valeur']].groupby("zone").sum()

In [112]:
# Affichage après trie des 10 pays qui ont bénéficié le plus de l'aide alimentaire
aide_pays.nlargest(10, 'Valeur')

                                      Valeur
zone
République arabe syrienne         1858943000
Éthiopie                          1381294000
Yémen                             1206484000
Soudan du Sud                      695248000
Soudan                             669784000
Kenya                              552836000
Bangladesh                         348188000
Somalie                            292678000
République démocratique du Congo   288502000
Niger                              276344000

### 3.8 - Evolution des 5 pays qui ont le plus bénéficiés de l'aide alimentaire entre 2013 et 2016

In [115]:
# Création d'un dataframe avec la zone, l'année et l'aide alimentaire puis groupby sur zone et année 
évolution5Pays = aideAlimentaire[['zone', 'Année', 'Valeur']]
évolution5Pays = évolution5Pays.groupby(['zone', 'Année']).sum().reset_index()

In [117]:
# Création d'une liste contenant les 5 pays qui ont le plus bénéficiées de l'aide alimentaire
liste5Pays = ['République arabe syrienne','Éthiopie','Yémen','Soudan du Sud','Soudan']

In [119]:
# On filtre sur le dataframe avec notre liste
exclusivement5Pays = évolution5Pays.loc[évolution5Pays['zone'].isin(liste5Pays),:]

In [121]:
# Affichage des pays avec l'aide alimentaire par année
exclusivement5Pays

                          zone  Année     Valeur
157  République arabe syrienne   2013  563566000
158  République arabe syrienne   2014  651870000
159  République arabe syrienne   2015  524949000
160  République arabe syrienne   2016  118558000
189                     Soudan   2013  330230000
190                     Soudan   2014  321904000
191                     Soudan   2015   17650000
192              Soudan du Sud   2013  196330000
193              Soudan du Sud   2014  450610000
194              Soudan du Sud   2015   48308000
214                      Yémen   2013  264764000
215                      Yémen   2014  103840000
216                      Yémen   2015  372306000
217                      Yémen   2016  465574000
225                   Éthiopie   2013  591404000
226                   Éthiopie   2014  586624000
227                   Éthiopie   2015  203266000

### 3.9 - Pays avec le moins de disponibilité par habitant

In [124]:
# Calcul de la disponibilité en kcal par personne par jour par pays
dispoPaysTotal = dispoAlimentaire[['Zone', 'Disponibilité alimentaire (Kcal/personne/jour)','Produit']].groupby('Zone').sum()

In [126]:
# Affichage des 10 pays qui ont le moins de dispo alimentaire par personne 
dispoPaysTotal.sort_values(by='Disponibilité alimentaire (Kcal/personne/jour)', ascending=True).head(10)

,Disponibilité alimentaire (Kcal/personne/jour),Produit
Zone,,
République centrafricaine,1879.0,"Abats ComestibleAlcool, non ComestibleAliments..."
Zambie,1924.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Madagascar,2056.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Afghanistan,2087.0,"Abats ComestibleAgrumes, AutresAliments pour e..."
Haïti,2089.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
République populaire démocratique de Corée,2093.0,Abats ComestibleAnimaux Aquatiques AutreAvoine...
Tchad,2109.0,"Abats ComestibleAlcool, non ComestibleAliments..."
Zimbabwe,2113.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Ouganda,2126.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Timor-Leste,2129.0,Abats ComestibleAliments pour enfantsAnanasAni...

### 3.10 - Pays avec le plus de disponibilité par habitant

In [129]:
# Affichage des 10 pays qui ont le plus de dispo alimentaire par personne 
dispoPaysTotal.sort_values(by='Disponibilité alimentaire (Kcal/personne/jour)', ascending=False).head(10)

,Disponibilité alimentaire (Kcal/personne/jour),Produit
Zone,,
Autriche,3770.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Belgique,3737.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Turquie,3708.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
États-Unis d'Amérique,3682.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Israël,3610.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Irlande,3602.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Italie,3578.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Luxembourg,3540.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Égypte,3518.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."
Allemagne,3503.0,"Abats ComestibleAgrumes, AutresAlcool, non Com..."

### 3.11 - Exemple de la Thaïlande pour le Manioc

In [132]:
# Création d'un dataframe avec uniquement la Thaïlande 
thailande = pd.merge(sousNutrition.loc[sousNutrition['Zone'] == 'Thaïlande',:], dispoAlimentaire.loc[dispoAlimentaire['Zone'] == 'Thaïlande'], on='Zone')

In [134]:
# Calcul de la sous nutrition en Thaïlande
print("La sous nutrition en Thïlande est de :", "{:.2f}".format(thailande['sous_nutrition'].sum()*100/thailande['Population_x'].sum()), "%")

La sous nutrition en Thïlande est de : 8.96 %

In [136]:
# On calcule la proportion exportée en fonction de la proportion
manioc = thailande.loc[thailande['Produit'] == 'Manioc',:]
print("La proportion exportée de Manioc est de :", "{:.2f}".format(manioc['Exportations - Quantité'].sum()*100/manioc['Production'].sum()), "%")

La proportion exportée de Manioc est de : 83.41 %

In [138]:
manioc

,Zone,Population_x,sous_nutrition,proportion par pays,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Population_y,dispo_kcal
50,Thaïlande,69209810.0,6200000.0,9.0,Manioc,vegetale,1800000.0,2081000.0,40.0,13.0,...,25214000.0,1250000.0,871000.0,1511000.0,30228000.0,0.0,0.0,0.0,69209810.0,1.010463e+12